config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :sandwiches
  
  resources :users do
    resources :sandwiches
  end
  
  root to: 'welcome#home'

  get '/cheese' => 'sandwiches#cheese'
  get '/grilled' => 'sandwiches#grilled'
  get '/open_faced' => 'sandwiches#open_faced'
  get '/peanut_butter' => 'sandwiches#peanut_butter'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/auth/github/callback' => 'sessions#create'
  
  get'/landing', to: "sandwiches#landing"
  post '/landing', to: "sandwiches#landing"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filling.rb
class Filling < ApplicationRecord
    has_many :sandwich_fillings
    has_many :sandwiches, through: :sandwich_fillings
    
    accepts_nested_attributes_for :sandwich_fillings, reject_if: :all_blank
    
end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
    belongs_to :user, optional: true
    has_many :sandwich_fillings, dependent: :delete_all
    has_many :fillings, through: :sandwich_fillings

    accepts_nested_attributes_for :sandwich_fillings
    
    validates :sandwich_name, presence: true
    validates :bread_name, presence: true

    scope :grilled, -> { where(grill: true).order(sandwich_name: :asc) }
    scope :open_faced, -> { where(open_face: true).order(sandwich_name: :asc) }
    scope :peanut_butter, -> { includes(:fillings).where(:fillings => { filling_name: "peanut butter" }).order(sandwich_name: :asc) }
    scope :cheese, -> { eager_load(:fillings).where( "fillings.filling_name LIKE ?", '%cheese%' ).order(sandwich_name: :asc) }
 
    def sandwich_fillings_attributes=(sandwich_fillings_attributes)
        self.sandwich_fillings.destroy_all
        sandwich_fillings_attributes.values.each do |sandwich_filling_attributes|
            unless sandwich_filling_attributes[:filling_name].blank?
            sandwich_filling = SandwichFilling.new(sandwich_filling_attributes)
            self.sandwich_fillings << sandwich_filling
          end
        end
    end

end

app/models/sandwich_filling.rb
class SandwichFilling < ApplicationRecord
  belongs_to :sandwich
  belongs_to :filling

  def filling_name
    self.filling.filling_name if self.filling
  end

  def filling_name=(name)
    self.filling = Filling.find_or_create_by(filling_name: name)
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :sandwiches
   
    has_secure_password
    
    validates :email, presence: true
    validates :email, uniqueness: true 

    def self.find_or_create_by_omniauth(auth_hash)
        self.where(:email => auth_hash["info"]["email"]).first_or_create do |user|
            user.password = SecureRandom.hex
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in?

  helper_method :current_user
    
  #for redirects
  def current_user
    if session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  #for controllers
  def require_login
    redirect_to login_path unless logged_in?
  end
  
  #for views, if helper method
  def logged_in?
    !!current_user
  end
  
end

app/controllers/sandwich_fillings_controller.rb
class SandwichFillingsController < ApplicationController
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController

    before_action :require_login

    def landing
    end

    def index
        if params[:user_id] && current_user.id == params[:user_id].to_i
          @user = current_user
          @sandwiches = @user.sandwiches.order(:sandwich_name) || 
          respond_to do |f|
            f.html {render :index}
            f.json {render json: @sandwiches}
          end
        elsif params[:user_id]
          flash[:alert] = "Leave my provolone! (You can't view another user's sandwiches)"
        else
          @sandwiches = Sandwich.all.order(:sandwich_name)
          respond_to do |f|
            f.html {render :index}
            f.json {render json: @sandwiches}
          end
        end
    end

    def new
        if params[:user_id] && current_user.id == params[:user_id].to_i
            @user = current_user
            @sandwich = Sandwich.new(user_id: params[:user_id])
            8.times {@sandwich.sandwich_fillings.build}
            if params[:layout] && params[:layout] == "false"
                render :new, layout: false
            else
                render :new
            end
        else
            flash[:alert] = "Leave my provolone! (You can't create a sandwich for another user)"
            redirect_to sandwiches_path
      end
    end

    def create
        @sandwich = Sandwich.new(sandwich_params)
        @user = User.find_by(id: params[:user_id])
        if @sandwich.save
            render json: @sandwich, status: 201
        else
            render json: @sandwich, status: 406
        end
    end

    def show
        @sandwich = Sandwich.find_by(id: params[:id])
        respond_to do |f|
          f.html {render :show}
          f.json {render json: @sandwich}
        end
    end

    def edit
        @sandwich = Sandwich.find_by(id: params[:id])
        @user = current_user
        if !@sandwich
            flash[:alert] = "Sorry, sandwich not found"
            redirect_to user_sandwiches_path
        end 
        4.times {@sandwich.sandwich_fillings.build}
    end

    def cheese
        @sandwiches = Sandwich.cheese
    end
    
    def grilled
        @sandwiches = Sandwich.grilled
    end

    def open_faced
        @sandwiches = Sandwich.open_faced
    end

    def peanut_butter
        @sandwiches = Sandwich.peanut_butter
    end

    def update
        @sandwich = Sandwich.find_by(id: params[:id])
        @sandwich.update(sandwich_params)
        redirect_to sandwich_path(@sandwich)
    end

    def destroy
        sandwich = Sandwich.find(params[:id])
        sandwich.destroy
        redirect_to user_sandwiches_path
    end

    private

    def sandwich_params
        params.require(:sandwich).permit(
            :sandwich_name, :bread_name, :grill, :open_face, :user_id, 
                sandwich_fillings_attributes: [:id, :quantity, :filling_name])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
    
  def create
    if auth_hash = request.env["omniauth.auth"]
      @user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = @user.id
      redirect_to landing_path
    else
      @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id 
      redirect_to landing_path
      else
        render :new
      end
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to landing_path
    else
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def human_boolean(boolean)
    boolean ? "yes" : "no"
  end

  def require_login
    redirect_to root_path unless logged_in?
  end
    
  def logged_in?
    !!current_user
  end
    
  def current_user
    @_current_user ||= User.find_by(:id => session[:user_id])
  end

end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sandwich_fillings_helper.rb
module SandwichFillingsHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsProjectSandwichPlatterJS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

<body>
  <% if current_user %>
  <h1>Sandwich Choices</h1>
  <h5>
  <a id="my-sandwiches" href="/users/<%=current_user.id%>/sandwiches">My Sandwiches </a>
  <br>
  <a id="all-sandwiches" href="/sandwiches">All Sandwiches</a>
  <br>
  <a id="create-new-sandwich" href="/users/<%=current_user.id%>/sandwiches/new">Build a New Sandwich </a>
  <br>
  <%= link_to "Log out", logout_path%><br>
  </h5>
  <%end%>
    <%= yield %>
</body>

</html>

app/views/sandwiches/_form.html.erb
<% if @sandwich.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@sandwich.errors.count, "error") %>
      prohibited this sandwich from being saved:
    </h2>
    <ul>
    <% @sandwich.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@user, @sandwich] do |f| %>
<%= f.hidden_field :user_id%>
<h3>
<p>
  <%= f.label :sandwich_name, 'Name Your Sandwich:' %>
  <%= f.text_field :sandwich_name %></p>
<p>
  <%= f.label :bread_name, "What kind of bread?" %>
  <%= f.text_field :bread_name %>
  <%= f.label :grill, "Grill It" %>
  <%= f.check_box :grill %>
  <%= f.label :open_face, "Make it Open Face" %>
  <%= f.check_box :open_face %></p>
    <p>
    <%= f.fields_for :sandwich_fillings do |j|%>
    <%= j.label :filling_name, "Spread/Filling" %>
    <%= j.text_field :filling_name %>
    <%= j.label :quantity, "Quantity" %>
    <%= j.text_field :quantity %><br>
    <br>
    <% end %>

<%= f.submit %>
</h3>

<% end %>

app/views/sandwiches/_list.html.erb
<h3>

<%= form_tag  do %>
<%=text_field_tag 'Search'%><br>
<input type="submit" value="Submit">
<p>
<%end%>

<%@sandwiches.each do |sandwich|%>
<%= link_to sandwich.sandwich_name, sandwich_path(sandwich)%>
<br>
<% end %>
</h3>
<h5>

app/views/sandwiches/_sandwich.html.erb
<h1><%= @sandwich.sandwich_name%> Sandwich</h1>
<h2>
Grilled: <%= human_boolean(@sandwich.grill) %><br>
Open-Faced: <%= human_boolean(@sandwich.open_face) %><br>
Bread: <%= @sandwich.bread_name %><br>
<br>
Spreads/Fillings:<br>
</h2>
<h3>
<% sandwich.sandwich_fillings.each do |sf|%>
<%= sf.filling.filling_name%> <%= sf.quantity%><br>
<%end%>
</h3>

<h5>
<%= link_to "All Sandwiches", sandwiches_path%><br>
<%= link_to "Cheese Sandwiches", cheese_path%><br>
<%= link_to "Grilled Sandwiches", grilled_path%><br>
<%= link_to "Open-Faced Sandwiches", open_faced_path%><br>
<%= link_to "Peanut Butter Sandwiches", peanut_butter_path%><br>
<br>
<%= link_to "My Sandwiches", user_sandwiches_path(current_user)%><br>
<%= link_to "Create a New Sandwich", new_user_sandwich_path(current_user)%><br>
<br>
<%= link_to "Log out", logout_path%><br>
</h5>

app/views/sandwiches/cheese.html.erb
<body class=cheese>

<h1>Cheese Sandwiches</h1>
<%= render partial: 'list', locals: {user: @user, sandwich: @sandwich} %>

</body>

app/views/sandwiches/edit.html.erb
<body class=new-sandwich>

<h1>Edit <%=@sandwich.sandwich_name%> Sandwich</h1>
<%= render partial: 'form', locals: {user: @user, sandwich: @sandwich} %>

</body>

app/views/sandwiches/grilled.html.erb
<body class=grilled>

<h1>Grilled Sandwiches</h1>
<%= render partial: 'list', locals: {user: @user, sandwich: @sandwich} %>

</body>

app/views/sandwiches/index.html.erb
<body class=sandwiches-index>

<h2>
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
</h2>

<h1>All Sandwiches</h1>
<%= render partial: 'list', locals: {user: @user, sandwich: @sandwich} %>

</body>

app/views/sandwiches/landing.html.erb
<body class=sandwiches-index>

<div id="ajax-content"></div>

</body>

app/views/sandwiches/new.html.erb
<body class=new-sandwich>

<h1>Build a New Sandwich</h1>
<%= render partial: 'form', locals: {user: @user, sandwich: @sandwich} %>

</body>

app/views/sandwiches/open_faced.html.erb
<body class=open-faced>

<h1>Open-Faced Sandwiches</h1>
<%= render partial: 'list', locals: {user: @user, sandwich: @sandwich} %>

</body>

app/views/sandwiches/peanut_butter.html.erb
<body class=peanut_butter>

<h1>Peanut Butter Sandwiches</h1>
<%= render partial: 'list', locals: {user: @user, sandwich: @sandwich} %>

</body>

app/views/sandwiches/show.html.erb
<body class=show-sandwich>

<%= render partial: 'sandwich', locals: {sandwich: @sandwich} %>

<%= render partial: 'form', locals: {user: @user, sandwich: @sandwich} %>

<% if current_user == @sandwich.user %>
<%= link_to "Edit Sandwich", edit_user_sandwich_path(current_user, @sandwich) %><br>
<%= link_to "Delete This Sandwich", user_sandwich_path(current_user, @sandwich), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

</body>

app/views/users/new.html.erb
<body class=users-new>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1> Sign Up for Sandwich Platter </h1>
<h2>
<%= form_for @user do |f| %>
<%= f.label :email, "Enter your email"%>
<%= f.email_field :email %>
<br>
<%= f.label :password, "Enter your password"%>
<%= f.password_field :password %>
<br>
<%= f.submit "Open Sesame!"%>
<%end%>
</h2>

</body>

app/views/welcome/home.html.erb
<body class=sandwiches-index>

<h1>Welcome to Sandwich Platter</h1>
<h2>We've got quite a spread here!</h2>

<p><%= link_to "Login", login_path %></p>
<p><%= link_to('Login with GitHub', '/auth/github') %>
<p><%= link_to "Sign Up", new_user_path %></p>

</body>